# Generated by Django 4.2.16 on 2026-09-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_department_code_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_REVIEW', 'Manager Review'), ('HR_REVIEW', 'HR Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('reason', models.CharField(choices=[('BETTER_OPPORTUNITY', 'Better Opportunity'), ('PERSONAL_REASONS', 'Personal Reasons'), ('HIGHER_EDUCATION', 'Higher Education'), ('RELOCATION', 'Relocation'), ('HEALTH_REASONS', 'Health Reasons'), ('FAMILY_COMMITMENT', 'Family Commitment'), ('CAREER_CHANGE', 'Career Change'), ('COMPENSATION', 'Compensation'), ('WORK_ENVIRONMENT', 'Work Environment'), ('OTHER', 'Other')], max_length=50)),
                ('resignation_date', models.DateField()),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_requests', to='employees.employee')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_resignations', to=settings.AUTH_USER_MODEL)),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviewed_resignations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_resignations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_resignationrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
