# Generated by Django 4.2.16 on 2026-09-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_REVIEW', 'Manager Review'), ('HR_REVIEW', 'HR Review'), ('APPROVED', 'Approved'), ('NOTICE_PERIOD', 'Notice Period'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='NoticePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EARLY_RELEASE_REQUESTED', 'Early Release Requested'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=30)),
                ('notice_period_start_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_last_working_day', models.DateField(blank=True, null=True)),
                ('actual_last_working_day', models.DateField(blank=True, null=True)),
                ('notice_comments', models.TextField(blank=True)),
                ('early_release_requested_at', models.DateTimeField(blank=True, null=True)),
                ('early_release_request_reason', models.TextField(blank=True)),
                ('early_release_date', models.DateField(blank=True, null=True)),
                ('early_release_approved', models.BooleanField(blank=True, null=True)),
                ('early_release_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('early_release_review_notes', models.TextField(blank=True)),
                ('notice_extension_date', models.DateField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True)),
                ('extension_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_notice_periods', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notice_periods', to=settings.AUTH_USER_MODEL)),
                ('early_release_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_release_requests', to=settings.AUTH_USER_MODEL)),
                ('early_release_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_release_reviews', to=settings.AUTH_USER_MODEL)),
                ('extension_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_extensions', to=settings.AUTH_USER_MODEL)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notice_period', to='offboarding.resignationrequest')),
            ],
            options={
                'db_table': 'offboarding_noticeperiod',
            },
        ),
    ]
