# Generated by Django 4.2.16 on 2026-09-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_code_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0002_notice_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsibility', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('RECEIVER_REVIEW', 'Receiver Review'), ('MANAGER_REVIEW', 'Manager Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('receiver_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kt_assigned', to='employees.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_created', to=settings.AUTH_USER_MODEL)),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_manager_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_knowledgetransfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='kt_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='kt_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_phase_completed_resignations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='employees.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee')),
            ],
            options={
                'db_table': 'offboarding_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KTDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_documents_added', to=settings.AUTH_USER_MODEL)),
                ('knowledge_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='offboarding.knowledgetransfer')),
            ],
            options={
                'db_table': 'offboarding_ktdocument',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgetransfer',
            name='offboarding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kt_items', to='offboarding.resignationrequest'),
        ),
        migrations.AddField(
            model_name='knowledgetransfer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_items', to='offboarding.project'),
        ),
        migrations.AddField(
            model_name='knowledgetransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kt_receiving', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='knowledgetransfer',
            name='receiver_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kt_receiver_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
