# Generated by Django 4.2.16 on 2026-09-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_code_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0003_knowledge_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=40, unique=True)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('ID_CARD', 'ID Card'), ('ACCESS_CARD', 'Access Card'), ('SIM_CARD', 'SIM Card'), ('OTHER', 'Other')], max_length=20)),
                ('asset_name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('CLEARED', 'Cleared')], default='ASSIGNED', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('NON_FUNCTIONAL', 'Non Functional')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='employees.employee')),
            ],
            options={
                'db_table': 'offboarding_asset',
                'ordering': ['asset_id'],
            },
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='clearance_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='clearance_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_phase_completed_resignations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('HR', 'HR'), ('MANAGER', 'Manager')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CLEARED', 'Cleared'), ('REJECTED', 'Rejected'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clearances', to=settings.AUTH_USER_MODEL)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_department_clearances', to=settings.AUTH_USER_MODEL)),
                ('offboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_clearances', to='offboarding.resignationrequest')),
            ],
            options={
                'db_table': 'offboarding_departmentclearance',
                'ordering': ['department'],
                'unique_together': {('offboarding_request', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ClearanceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('department_clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='offboarding.departmentclearance')),
            ],
            options={
                'db_table': 'offboarding_clearancechecklistitem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssetClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('CLEARED', 'Cleared'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('REJECTED', 'Rejected')], default='RETURN_PENDING', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition_at_return', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('NON_FUNCTIONAL', 'Non Functional')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='offboarding.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_clearances', to='employees.employee')),
                ('offboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_clearances', to='offboarding.resignationrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_asset_clearances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_assetclearance',
                'ordering': ['-created_at'],
                'unique_together': {('offboarding_request', 'asset')},
            },
        ),
    ]
