# Generated by Django 4.2.16 on 2026-09-24 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_code_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0004_asset_clearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settlement_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlements', to='employees.employee')),
                ('offboarding_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='offboarding.resignationrequest')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_settlements', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_finalsettlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('primary_reason', models.CharField(blank=True, choices=[('CAREER_GROWTH', 'Career Growth'), ('NEW_OPPORTUNITY', 'New Opportunity'), ('HIGHER_STUDIES', 'Higher Studies'), ('PERSONAL_REASONS', 'Personal Reasons'), ('RELOCATION', 'Relocation'), ('COMPENSATION', 'Compensation'), ('WORK_ENVIRONMENT', 'Work Environment'), ('MANAGEMENT', 'Management'), ('ROLE_CHANGE', 'Role Change'), ('OTHER', 'Other')], max_length=30)),
                ('secondary_reason', models.CharField(blank=True, choices=[('CAREER_GROWTH', 'Career Growth'), ('NEW_OPPORTUNITY', 'New Opportunity'), ('HIGHER_STUDIES', 'Higher Studies'), ('PERSONAL_REASONS', 'Personal Reasons'), ('RELOCATION', 'Relocation'), ('COMPENSATION', 'Compensation'), ('WORK_ENVIRONMENT', 'Work Environment'), ('MANAGEMENT', 'Management'), ('ROLE_CHANGE', 'Role Change'), ('OTHER', 'Other')], max_length=30)),
                ('overall_experience', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('manager_feedback', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('work_environment_feedback', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('role_feedback', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('growth_feedback', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('compensation_feedback', models.PositiveSmallIntegerField(choices=[(0, 'Not Answered'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('what_went_well', models.TextField(blank=True)),
                ('what_could_improve', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('would_rejoin', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='NOT_STARTED', max_length=20)),
                ('hr_review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_exit_interviews', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='employees.employee')),
                ('offboarding_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='offboarding.resignationrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exit_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_exitinterview',
                'ordering': ['-created_at'],
            },
        ),
    ]
