# Generated by Django 4.2.16 on 2026-09-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0005_settlement_exit_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrequest',
            name='final_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='final_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='final_review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='final_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='final_review_status',
            field=models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY_FOR_REVIEW', 'Ready for Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_READY', max_length=20),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='final_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reviewed_resignations', to=settings.AUTH_USER_MODEL),
        ),
    ]
