# Generated by Django 4.2.16 on 2026-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0006_final_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrequest',
            name='exit_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
