# Generated by Django 4.2.16 on 2026-10-08 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offboarding', '0007_resignationrequest_exit_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrequest',
            name='asset_declaration_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='asset_declaration_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_declarations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='asset_declaration_notes',
            field=models.TextField(blank=True),
        ),
    ]
