# Generated by Django 4.2.16 on 2026-10-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0008_resignationrequest_asset_declaration_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrequest',
            name='asset_declaration_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
