# Generated by Django 4.2.16 on 2026-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESIGNATION_SUBMITTED', 'Resignation Submitted'), ('RESIGNATION_APPROVED', 'Resignation Approved'), ('RESIGNATION_REJECTED', 'Resignation Rejected'), ('RESIGNATION_CANCELLED', 'Resignation Cancelled'), ('ACTION_REQUIRED', 'Action Required'), ('STATUS_UPDATE', 'Status Update'), ('MANAGER_APPROVAL_REQUIRED', 'Manager Approval Required'), ('HR_REVIEW_REQUIRED', 'HR Review Required'), ('NOTICE_UPDATED', 'Notice Updated'), ('EARLY_RELEASE_REQUESTED', 'Early Release Requested'), ('EARLY_RELEASE_DECISION', 'Early Release Decision'), ('NOTICE_COMPLETED', 'Notice Completed'), ('KT_ASSIGNED', 'KT Assigned'), ('KT_SUBMITTED', 'KT Submitted'), ('KT_CHANGES_REQUESTED', 'KT Changes Requested'), ('KT_APPROVED', 'KT Approved'), ('KT_COMPLETED', 'KT Completed'), ('ASSET_RETURN_REQUIRED', 'Asset Return Required'), ('ASSET_RETURNED', 'Asset Returned'), ('ASSET_VERIFICATION_REQUIRED', 'Asset Verification Required'), ('CLEARANCE_ACTION_REQUIRED', 'Clearance Action Required'), ('CLEARANCE_COMPLETED', 'Clearance Completed'), ('SETTLEMENT_PREPARED', 'Settlement Prepared'), ('SETTLEMENT_REVIEW_REQUIRED', 'Settlement Review Required'), ('SETTLEMENT_APPROVED', 'Settlement Approved'), ('SETTLEMENT_REJECTED', 'Settlement Rejected'), ('EXIT_INTERVIEW_REQUIRED', 'Exit Interview Required'), ('EXIT_INTERVIEW_SUBMITTED', 'Exit Interview Submitted'), ('EXIT_INTERVIEW_REVIEWED', 'Exit Interview Reviewed'), ('FINAL_REVIEW_REQUIRED', 'Final Review Required'), ('FINAL_APPROVAL', 'Final Approval'), ('FINAL_REJECTION', 'Final Rejection'), ('DOCUMENT_GENERATED', 'Document Generated'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_RELEASED', 'Document Released'), ('DOCUMENT_REVOKED', 'Document Revoked'), ('EXIT_REMINDER', 'Exit Reminder')], max_length=50),
        ),
    ]
