# Generated by Django 4.2.16 on 2026-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        # 1. Add new fields to Department
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # 2. Add new fields to Employee (all safe additions)
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(
                choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')],
                default='FULL_TIME',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        # 3. Fix the department FK (was not null, now allows null/blank)
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees',
                to='employees.department',
            ),
        ),
        # 4. Rename the old designation CharField so we can reuse the column name
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='designation_legacy',
        ),
        # 5. Create the Designation model
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='designations',
                    to='employees.department',
                )),
            ],
            options={
                'db_table': 'employees_designation',
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        # 6. Add the new designation FK (nullable so no data issue)
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees',
                to='employees.designation',
            ),
        ),
        # 7. Remove the legacy text column
        migrations.RemoveField(
            model_name='employee',
            name='designation_legacy',
        ),
        # 8. Add Department.head FK (after Employee model exists)
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='headed_department',
                to='employees.employee',
            ),
        ),
    ]
