# Generated by Django 4.2.16 on 2026-09-24 15:02

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_department_code_department_description_and_more'),
        ('offboarding', '0006_final_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('signatory_name', models.CharField(blank=True, max_length=150)),
                ('signatory_designation', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_companyprofile',
            },
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'documents_documentcounter',
            },
        ),
        migrations.CreateModel(
            name='OffboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('FULL_FINAL_SETTLEMENT', 'Full & Final Settlement'), ('EXIT_CLEARANCE', 'Exit Clearance Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('document_number', models.CharField(max_length=60, unique=True)),
                ('document_title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.document_upload_path)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('REVOKED', 'Revoked')], default='GENERATED', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_documents', to='employees.employee')),
                ('offboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='offboarding.resignationrequest')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_documents', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_documents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_offboardingdocument',
                'ordering': ['-created_at'],
            },
        ),
    ]
